# Generated by Django 5.2.4 on 2025-08-31 21:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dmzw6gxps/image/upload/v1753708918/s2s5ltkbp0lr5gt9pote.jpg', max_length=255, null=True, verbose_name='image')),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
