# Generated by Django 5.2.4 on 2025-08-27 16:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dmzw6gxps/image/upload/v1753708918/s2s5ltkbp0lr5gt9pote.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
