# Generated by Django 5.2.4 on 2025-08-31 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.IntegerField(choices=[(0, '9:00-9:45'), (1, '10:00-10:45'), (2, '11:00-11:45'), (3, '14:00-14:45'), (4, '15:00-15:45'), (5, '16:00-16:45'), (6, '17:00-17:45'), (7, '18:00-18:45')], default=0)),
                ('guests', models.PositiveIntegerField()),
                ('canceled', models.BooleanField(default=False)),
                ('cancel_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'time')},
            },
        ),
    ]
