# Generated by Django 5.2.4 on 2025-08-31 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancel_token',
        ),
    ]
