# Generated by Django 5.2.4 on 2025-08-07 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
