# Generated by Django 5.2.4 on 2025-08-07 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_cancel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancel_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
